include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_unused_constructor_parameters: true
    directives_ordering: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true
    use_full_hex_values_for_flutter_colors: true
    omit_local_variable_types: false

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.gr.dart
    - lib/**/*.freezed.dart
    - lib/**/*.chopper.dart
  errors:
    invalid_annotation_target: ignore

