targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: snake
          ignore_unannotated: false
          include_if_null: false
#      moor_generator:
#        options:
#          generate_connect_constructor: true
#          data_class_to_companions: false
#          write_from_json_string_constructor: false
#          generate_values_in_copy_with: false
      freezed:
        options:
          make_collections_unmodifiable: false
