name: kaimovies
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  chopper: ^6.1.1
  flutter_bloc: ^8.1.2
  flutter_card_swiper: ^6.0.0
  flutter_native_splash: ^2.2.19
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  json_annotation: ^4.7.0
  provider: ^6.0.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  go_router_builder: ^2.3.4
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_logo.png"

flutter_native_splash:
  image: assets/splash_logo.png
  color: "1b1c26"
  android: true
  android_12:
    image: assets/splash_logo_12.png
    color: "1b1c26"
  android_disable_fullscreen: true
  ios: true
  web: false

#flutter_gen:
#  package_name: OfficelessAssets